services:
  # Backend API Service
  - type: web
    name: betting-app-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: MONGODB_URL
        sync: false # Set this in Render dashboard
      - key: DATABASE_NAME
        value: betting_db
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: CORS_ORIGINS
        value: https://betting-app-frontend.onrender.com # Replace with your frontend URL
      - key: STRIPE_SECRET_KEY
        sync: false # Set this in Render dashboard
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false # Set this in Render dashboard
      - key: STRIPE_WEBHOOK_SECRET
        sync: false # Set this in Render dashboard

  # Frontend Static Site
  - type: static_site
    name: betting-app-frontend
    buildCommand: cd frontend && flutter pub get && flutter build web --release
    publishPath: frontend/build/web
    headers:
      - path: /*
        headers:
          - key: X-Frame-Options
            value: DENY
          - key: X-Content-Type-Options
            value: nosniff

  # Redis Service (optional - for caching)
  - type: redis
    name: betting-app-redis
    plan: free # or starter for production
    ipAllowList: [] # Allow all IPs or specify your backend IPs
