services:
  # Backend API Service
  - type: web
    name: betting-app-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: MONGODB_URL
        sync: false # Set this in Render dashboard
      - key: DATABASE_NAME
        value: betting_db
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: CORS_ORIGINS
        value: "*" # Will update after frontend deployment
      - key: STRIPE_SECRET_KEY
        sync: false # Set this in Render dashboard
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false # Set this in Render dashboard
      - key: STRIPE_WEBHOOK_SECRET
        sync: false # Set this in Render dashboard
